import Navbar from '../components/Navbar.jsx';
import Footer from '../components/Footer.jsx';
import SectionHeader from '../components/SectionHeader.jsx';

const SECTIONS = [
    {
        title: '1. What we collect',
        body: [
            'Account data: your username, email address and password hash — the minimum needed to run your account.',
            'Service data: deployment logs, resource usage and error output generated by your apps, used for monitoring, restarts and debugging.',
            'Support data: whatever you send us when you contact support, so we can actually help.',
        ],
    },
    {
        title: '2. What we never do',
        body: [
            'We never sell your personal data. We never read your application code or database contents except when you explicitly ask us to debug something.',
            'We run no third-party ad trackers on the dashboard. Analytics, if any, are self-hosted and aggregated.',
        ],
    },
    {
        title: '3. How data is protected',
        body: [
            'Traffic is encrypted in transit (TLS) and sensitive fields are encrypted at rest. Production access is limited to a small number of engineers and fully logged.',
            'Backups are stored encrypted and retained for 30 days, then rotated out automatically.',
        ],
    },
    {
        title: '4. Your rights',
        body: [
            'You can export or delete your data at any time from the dashboard, or by emailing support. Deleting your account removes your data within 30 days, except for invoices we must keep for tax records.',
        ],
    },
    {
        title: '5. Cookies',
        body: [
            'We use strictly necessary cookies to keep you logged in and remember preferences. No advertising or cross-site tracking cookies.',
        ],
    },
    {
        title: '6. Contact',
        body: [
            'Questions about privacy? Reach us any time — the fastest way is the contact page or our Discord server.',
        ],
    },
];

export default function Privacy() {
    return (
        <div className="min-h-screen bg-background text-foreground">
            <Navbar />
            <main className="container-page pt-36 pb-16">
                <SectionHeader
                    tag="Legal"
                    title={
                        <>
                            Privacy <span className="gradient-text">Policy</span>
                        </>
                    }
                    subtitle="Last updated: September 2026"
                />

                <div className="mx-auto flex max-w-[800px] flex-col gap-6">
                    {SECTIONS.map((section) => (
                        <article
                            key={section.title}
                            className="rounded-lg border border-hairline bg-card p-7 max-[480px]:p-6"
                        >
                            <h3 className="mb-3 text-[1.1rem] font-bold">{section.title}</h3>
                            <div className="flex flex-col gap-3">
                                {section.body.map((paragraph, i) => (
                                    <p
                                        key={i}
                                        className="text-[0.92rem] leading-[1.75] text-ink-secondary"
                                    >
                                        {paragraph}
                                    </p>
                                ))}
                            </div>
                        </article>
                    ))}
                </div>
            </main>
            <Footer />
        </div>
    );
}
